name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests (pytest)
        run: pytest -q

      # Optional: only runs if you commit a sample mesh file (e.g., sample.stl)
      - name: Smoke test POC script if sample mesh exists
        if: ${{ hashFiles('sample.stl') != '' }}
        run: |
          python mesh_metadata.py sample.stl
          test -f metadata.json && echo "metadata.json generated ✅"
